//go:build ignore

package metrics
package metrics













































































}	}, nil		NetBytesRecv: recv,		NetBytesSent: sent,		DiskPercent: d.UsedPercent,		DiskTotal:  d.Total,		DiskUsed:   d.Used,		MemPercent: vm.UsedPercent,		MemTotal:   vm.Total,		MemUsed:    vm.Used,		CPUCores:   cores,		CPUPercent: cpuPercent,	return HostMetrics{	}		recv = ioCounters[0].BytesRecv		sent = ioCounters[0].BytesSent	if len(ioCounters) > 0 {	var sent, recv uint64	ioCounters, _ := net.IOCountersWithContext(ctx, false)	// Net (cumulative)	}		d = &disk.UsageStat{}		// allow running on systems without /	if err != nil {	d, err := disk.UsageWithContext(ctx, "/")	// Disk	}		return HostMetrics{}, err	if err != nil {	vm, err := mem.VirtualMemoryWithContext(ctx)	// Memory	}		cores, _ = cpu.CountsWithContext(ctx, true)	if cores == 0 {	cores := len(info)	info, _ := cpu.InfoWithContext(ctx)	}		cpuPercent = percents[0]	if len(percents) > 0 {	cpuPercent := 0.0	}		return HostMetrics{}, err	if err != nil {	percents, err := cpu.PercentWithContext(ctx, 200*time.Millisecond, false)	// CPUfunc Collect(ctx context.Context) (HostMetrics, error) {}	NetBytesRecv uint64 `json:"netBytesRecv"`	NetBytesSent uint64 `json:"netBytesSent"`	DiskPercent float64 `json:"diskPercent"`	DiskTotal   uint64  `json:"diskTotal"`	DiskUsed    uint64  `json:"diskUsed"`	MemPercent float64 `json:"memPercent"`	MemTotal   uint64  `json:"memTotal"`	MemUsed    uint64  `json:"memUsed"`	CPUCores   int     `json:"cpuCores"`	CPUPercent float64 `json:"cpuPercent"`type HostMetrics struct {)	"github.com/shirou/gopsutil/v3/net"	"github.com/shirou/gopsutil/v3/mem"	"github.com/shirou/gopsutil/v3/disk"	"github.com/shirou/gopsutil/v3/cpu"	"time"	"context"import (